<?php

namespace BlogBundle\Repository;

/**
 * Post1Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Post1Repository extends \Doctrine\ORM\EntityRepository
{
}
